Add loadAllFixtures method
liip/LiipTestFixturesBundle pull request #60
Opened 2020-03-14 16:30 UTC by LucHamers

The loadAllFixtures behaves like the console command doctrine:fixtures:load, including using the correct order from DependentFixtureInterface/OrderedFixtureInterface and grouping from FixtureGroupInterface.

I had to change some reference names in existing fixtures, because the name "user" was used in several fixtures. This caused problems for the unit test which loads everything. I hope this is OK.

(this is my first pull request ever, so I hope I did everything correct. If not, please give me a message)

2020-03-27 17:02 UTC, alexislefebvre commented
Tests fail because `Doctrine\Bundle\FixturesBundle\FixtureGroupInterface` doesn't exist on older version of Doctrine.

We may test that this class exist, and if it's missing, show a message instead of executing the command.

2020-03-27 19:24 UTC, LucHamers commented
I have added a check which skips the test for older doctrine versions.

2021-04-12 23:10 UTC, alexislefebvre commented
Could you please rebase that PR?

2021-05-09 19:55 UTC, LucHamers commented
I rebased my pull request. I hope this works OK; had never done that.

2021-05-09 20:39 UTC, LucHamers commented
Same problem as before: symfony 3.4 is not working. As long as this version is supported by the bundle, the code will not work.

2021-05-09 22:24 UTC, alexislefebvre commented
Thanks for the rebase. We [switched the default branch from 1.x to 2.x](https://github.com/liip/LiipTestFixturesBundle/pull/107#issuecomment-835841981). You can rebase this PR on the 2.x branch.

2021-05-09 22:56 UTC, alexislefebvre commented on tests/Test/ConfigSqliteTest.php
> +        if (interface_exists(FixtureGroupInterface::class)) {
This condition can be removed for the `2.x` branch.

2021-05-09 23:00 UTC, alexislefebvre commented on src/Test/FixturesTrait.php
> +    protected function loadAllFixtures(array $groups = []): ?AbstractExecutor
That method will have to go there: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseTools/AbstractDatabaseTool.php

2021-05-09 23:01 UTC, alexislefebvre requested changes

2021-05-09 23:01 UTC, alexislefebvre commented on tests/Test/ConfigSqliteTest.php
> +            $fixtures = $this->loadAllFixtures(['wrongGroup']);
You'll be able to call `$this->databaseTool->loadAllFixtures(['wrongGroup'])`

2021-05-22 16:26 UTC, closed without merging

2021-05-22 16:26 UTC, LucHamers commented
Replaced this pull request by a new one, now based on branch 2.x